"use client";
import careers from "@/data/career-paths.generated.json";
import { useMemo, useRef, useState } from "react";
import { ArrowDown, Check, X } from "lucide-react";
import { useProgress } from "@/components/progress-provider";
import { calculateScore } from "@/lib/game";
import type { GameResult } from "@/types";
import { Result } from "./result";
export function CareerGame(){const[run,setRun]=useState(0);return <CareerRound key={run} again={()=>setRun(value=>value+1)}/>}
function CareerRound({again}:{again:()=>void}){const questions=useMemo(()=>[...careers].sort((a,b)=>a.id.localeCompare(b.id)).slice(0,20),[]),{complete}=useProgress();const[i,setI]=useState(0),[selected,setSelected]=useState<string|null>(null),[correct,setCorrect]=useState(0),[xp,setXp]=useState(0),[streak,setStreak]=useState(0),[best,setBest]=useState(0),[result,setResult]=useState<GameResult|null>(null);const start=useRef(Date.now()),q=questions[i];function answer(name:string){if(selected)return;setSelected(name);const yes=name===q.answer,next=yes?streak+1:0,earned=yes?calculateScore("career-path",1,1,next):0;setTimeout(()=>{if(i===questions.length-1){const gameResult={score:xp+earned,xp:xp+earned,correct:correct+(yes?1:0),total:questions.length,bestStreak:Math.max(best,next),elapsed:Math.round((Date.now()-start.current)/1000),mode:"Career Path"};complete(gameResult,"Career Path");setResult(gameResult)}else{setI(value=>value+1);setSelected(null);if(yes){setCorrect(value=>value+1);setXp(value=>value+earned);setStreak(next);setBest(value=>Math.max(value,next))}else setStreak(0)}},1000)}if(result)return <main className="game-shell"><Result result={result} onAgain={again}/></main>;return <main className="game-shell"><header className="game-hud"><div><span>PATH</span><strong>{i+1}<i>/{questions.length}</i></strong></div><div className="hud-progress"><i style={{width:`${i/questions.length*100}%`}}/></div><div><strong>{xp} XP</strong></div></header><section className="question-card"><div className="mode-label">CAREER PATH · 20 QUESTIONS</div><h1>WHO MADE THIS JOURNEY?</h1><div className="career-path">{q.clubs.map((club,index)=><div key={`${club}-${index}`}><span>{club.slice(0,3).toUpperCase()}</span><strong>{club}</strong>{index<q.clubs.length-1&&<ArrowDown/>}</div>)}</div><div className="answers two">{q.choices.map(choice=><button key={choice} disabled={!!selected} onClick={()=>answer(choice)} className={selected?(choice===q.answer?"correct":choice===selected?"wrong":"dim"):""}>{choice}{selected&&choice===q.answer?<Check/>:selected===choice?<X/>:null}</button>)}</div>{selected&&<div className={selected===q.answer?"feedback good":"feedback bad"}><strong>{selected===q.answer?`CORRECT · +${calculateScore("career-path",1,1,streak+1)} XP`:`THE PLAYER WAS ${q.answer.toUpperCase()}`}</strong><span>{q.nationality} · {q.position}</span></div>}</section></main>}
